<template>
		<div class="slack-layout">
			<div class="login-form">
				<div class="step-login" v-if="$route.params.slack_token">
					<h3 class="text-2xl font-bold text-center">Sign in with your NEAR account</h3>
					<h4 class="text-2xl mt-4 font-bold text-center">{{ nearUser }}</h4>
					<NearLoginButton class="mt-8" @click="requestNearLogin"></NearLoginButton>
				</div>
				<div class="step-success" v-else-if="this.walletAccount.isSignedIn && this.walletAccount.isSignedIn()">
					<h3 class="text-2xl font-bold text-center">Than you for Signing in with Near</h3>
				</div>
				<div class="step-token-missing" v-else>
					<h3 class="text-2xl leading-12 font-bold text-center">
						To login with Slack and Near<br>
						Please follow a link generated by the Near Slack App
					</h3>
				</div>
			</div>
		</div>
</template>

<script>

import NearLoginButton from '../components/NearLoginButton.vue'

export default {
	name: 'login',
	props: {
	},
	components: {
		NearLoginButton
	},
	data() {
		return {
			walletAccount: {},
			nearUser: 'test.testnet'
		};
	},
	created() {
		if (this.$route.params.slack_token) {
			console.log('this.$route.params.slack_token', this.$route.params.slack_token)
			this.authWithFirestore()
		}
	},
	beforeUnmount() {
	},
	mounted() {
	},
	methods: {
		authWithFirestore() {
			// TODO: Add code to initialzie connection with Firestore
		},
		requestNearLogin() {
			console.log('requestNearLogin Start')
			this.walletAccount.requestSignIn(
				this.nearUser,
				'Authorize Slack NEAR?'
			);
		}
	}
}
</script>

<style lang="scss" scoped>
a {
  color: #42b983;
}
.slack-layout {
	@apply flex items-center justify-center min-h-screen bg-gray-100;
	border-radius: 4px;
}
.login-form {
	@apply px-8 py-6 text-left bg-white shadow-lg text-near1-900;
	margin-bottom: 35%;
	& > div {
		@apply content-center items-center place-items-center justify-center justify-items-center
	}
}

</style>
