<template>
		<div class="slack-layout">
			<div class="login-form">
				<div class="step-success" v-if="$route.query.all_keys">
					<h3 class="text-2xl font-bold text-center">Thank you for Signing in with NEAR</h3>
				</div>
				<div class="step-login" v-else-if="$route.query.fb_token">
					<h3 class="text-2xl font-bold text-center">Sign in with your NEAR account</h3>
					<h4 class="text-2xl mt-4 font-bold text-center">{{ accountId }}</h4>
					<NearLoginButton class="mt-8" @click="requestNearLogin"></NearLoginButton>
				</div>
				<div class="step-token-missing" v-else>
					<h3 class="text-2xl leading-12 font-bold text-center">
						To login with Slack and Near<br>
						Please follow a link generated by the Near Slack App
					</h3>
				</div>
			</div>
		</div>
</template>

<script>
import * as nearAPI from 'near-api-js'
import { getAuth, signInWithCustomToken } from "firebase/auth";
import { doc, updateDoc } from "firebase/firestore";

import NearLoginButton from '../components/NearLoginButton.vue'
import nearConfig from '../config/nearConfig.js'

// const CONTRACT_NAME = 'maix.testnet';

export default {
	name: 'login',
	props: {
	},
	components: {
		NearLoginButton
	},
	data() {
		return {
			auth: null,
			config: null,
			near: null,
			walletAccount: {},
			accountId: null,
		};
	},
	created() {
	},
	async mounted() {
		console.log("Mounted")
		if (this.$route.query.fb_token) {
			await this.authFirestore()
			await this.initNearAPI()
		}
		if (this.$route.query.all_keys && !!'TODO: key is valid') {
			await this.updateUserNearFunctionKey()
		}
	},
	methods: {
		async authFirestore() {
			try {
				this.auth = getAuth();
				// console.log('authFirestore fb_token', this.$route.query.fb_token)
				let user = await signInWithCustomToken(this.auth, this.$route.query.fb_token)
				console.log('authFirestore user', user)
			} catch (e) {
				console.log('authFirestore err: ', e)
			}
		},
		async updateUserNearFunctionKey() {
			console.log('this.$route.query.all_keys', this.$route.query.all_keys)
			const userId = this.auth.currentUser.uid
			return updateDoc(doc(this.$db, "users", userId), {
				near_account: this.$route.query.account_id,
				near_fn_key: this.$route.query.all_keys
			})
		},
		async initNearAPI() {
			try {
				const config = nearConfig.getConfig('testnet')
				const keyStore = new nearAPI.keyStores.BrowserLocalStorageKeyStore()
				console.log("keyStore", keyStore)
				if (keyStore) config.keyStore = keyStore
				
				// connect to NEAR
				this.near = await nearAPI.connect(config);
				this.walletAccount = new nearAPI.WalletConnection(this.near);
				this.accountId = this.walletAccount.getAccountId();
				
				// TODO: Tozi kod s kakva cel e? Az zapisvam token-a sled redirecta ot query params, no nz dali e pravilniq token
				// const key = await config.keyStore.getKey("testnet", "maix.testnet"); // tuk e problema
				// console.log("config.keyStore", key);
			} catch (e) {
				console.log('initNearAPI err', e)
				return Promise.reject(e)
			}
		},
		requestNearLogin() {
			console.log('requestNearLogin Start')
			this.walletAccount.requestSignIn();
		}
	}
}
</script>

<style lang="scss" scoped>
a {
  color: #42b983;
}
.slack-layout {
	@apply flex items-center justify-center min-h-screen bg-gray-100;
	border-radius: 4px;
}
.login-form {
	@apply px-8 py-6 text-left bg-white shadow-lg text-near1-900;
	margin-top: -30vh;
	& > div {
		@apply content-center items-center place-items-center justify-center justify-items-center
	}
}

</style>
