<template>
		<div class="slack-layout">
			<div class="login-form">
				<div class="step-login" v-if="$route.params.slack_token">
					<h3 class="text-2xl font-bold text-center">Sign in with your NEAR account</h3>
					<h4 class="text-2xl mt-4 font-bold text-center">{{ nearUser }}</h4>
					<NearLoginButton class="mt-8" @click="requestNearLogin"></NearLoginButton>
				</div>
				<div class="step-success" v-else-if="this.walletAccount.isSignedIn && this.walletAccount.isSignedIn()">
					<h3 class="text-2xl font-bold text-center">Than you for Signing in with Near</h3>
				</div>
				<div class="step-token-missing" v-else>
					<h3 class="text-2xl leading-12 font-bold text-center">
						To login with Slack and Near<br>
						Please follow a link generated by the Near Slack App
					</h3>
				</div>
			</div>
		</div>
</template>

<script>
import * as nearAPI from 'near-api-js'
import { collection, doc, setDoc } from "firebase/firestore"; 

import NearLoginButton from '../components/NearLoginButton.vue'

const CONTRACT_NAME = 'maix.testnet';

function getConfig (env) {
	switch (env) {
	case 'production':
	case 'mainnet':
		return {
			networkId: 'mainnet',
			nodeUrl: 'https://rpc.mainnet.near.org',
			contractName: CONTRACT_NAME,
			walletUrl: 'https://wallet.near.org',
			helperUrl: 'https://helper.mainnet.near.org'
		}
	case 'development':
	case 'testnet':
		return {
			networkId: 'testnet',
			nodeUrl: 'https://rpc.testnet.near.org',
			contractName: CONTRACT_NAME,
			walletUrl: 'https://wallet.testnet.near.org',
			helperUrl: 'https://helper.testnet.near.org'
		}
	default:
		throw Error(`Unconfigured environment '${env}'. Can be configured in src/config.js.`)
	}
}

export default {
	name: 'login',
	props: {
	},
	components: {
		NearLoginButton
	},
	data() {
		return {
			config: getConfig('development'),
			near: "nullirai",
			walletAccount: {},
			accountId: null,
		};
	},
	created() {
		if (this.$route.params.slack_token) {
			console.log('this.$route.params.slack_token', this.$route.params.slack_token)
			this.authWithFirestore()
		}
	},
	beforeUnmount() {
	},
	async mounted() {

		console.log("Mounted")

		const config = {
			...this.config,
			...{
				// creates keyStore using private key in local storage
				// *** REQUIRES SignIn using walletConnection.requestSignIn() ***
				keyStore: new nearAPI.keyStores.BrowserLocalStorageKeyStore()
			}
		};

		// connect to NEAR
		this.near = await nearAPI.connect(config);
		// // create wallet connection
		this.walletAccount = new nearAPI.WalletConnection(this.near);
		this.accountId = this.walletAccount.getAccountId();

		const key = await config.keyStore.getKey("testnet", "maix.testnet"); // tuk e problema
		
		console.log("config.keyStore", key);
	},
	methods: {
		authWithFirestore() {
			// TODO: Add code to initialzie connection with Firestore
		},
		requestNearLogin() {
			console.log('requestNearLogin Start')



			this.walletAccount.requestSignIn();
		}
	}
}
</script>

<style lang="scss" scoped>
a {
  color: #42b983;
}
.slack-layout {
	@apply flex items-center justify-center min-h-screen bg-gray-100;
	border-radius: 4px;
}
.login-form {
	@apply px-8 py-6 text-left bg-white shadow-lg text-near1-900;
	margin-bottom: 35%;
	& > div {
		@apply content-center items-center place-items-center justify-center justify-items-center
	}
}

</style>
